language: node_js
sudo: false
node_js:
- '0.12'
- '4'
- '5'
- '6'
deploy:
  provider: npm
  email: arnaud.lewis@gmail.com
  api_key:
    secure: R9LtyIpgqJkeiTigLdWsqrbdE/+sxVnlKKhufeJZIRJyxrlJDVpQJkA/xzFpypqDGCL7ZjtWh8nwk0d8SiljLMAR3xe4E1PlXKcGNQ1eVlwom++Ar7W4uizoRTVVADinzv2koowzx/mlqfiyeu/wC/B0Gap7HhUazrn9r2ezeFk=
  on:
    tags: true
    branch: master
    repo: prismicio/javascript-kit
after_script:
- codeclimate < coverage/lcov.info
addons:
  code_climate:
    repo_token: 25760a4ae3dea7404d3a3ef79951e0b6bf8808fcdb7f63bc1533610a9d8f936d
